### ISSUE TITLE
organizations formatted incorrectly to database

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone#1087]
https://oodikone.cs.helsinki.fi/faculties
This page crashes at least in production.

**Comment by esakemp** [comment]
Doesn't crash anymore but had to disable names of the faculties so now the page is pretty much useless. There is some weird happening with the database probably since the page works fine locally.

**Comment by esakemp** [comment]
old database had name: {'fi': 'lorem ipsum', 'en': 'lorem ipsum'}

currently updater formats it name: [{'text': 'lorem ipsum', 'langcode': 'fi'},{'text': 'lorem ipsum', 'langcode': 'en'}]
