### ISSUE TITLE
overview numbers are messed up

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#1205]
Something funky with transfer students

https://oodikone.cs.helsinki.fi/study-programme/KH50_005

![what jpg](https://user-images.githubusercontent.com/40692959/62479200-93e91380-b7b5-11e9-966c-7639e5b856fc.jpg)

**Comment by Rochet2** [comment]
Fixed in https://github.com/UniversityOfHelsinkiCS/oodikone/commit/39990fd704997e76b400a72a677aab704169bb88
