### ISSUE TITLE
study programme: student graduation in future

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#1397]
![image](https://user-images.githubusercontent.com/523235/64239792-8dab9b80-cf09-11e9-8839-b06ae0fcd7fa.png)

**Comment by Rochet2** [comment]
![image](https://user-images.githubusercontent.com/468816/64240696-04956400-cf0b-11e9-99ba-18ab20e6533c.png)

**Comment by Rochet2** [comment]
014714874
014584279

**Comment by esakemp** [comment]
for studentnumbers mentioned the problem has fixed. oodi can be bit slow to update the correct dates and this is why this happens. some fixes to updater have been issued and possibly fixed this.
