### ISSUE TITLE
programme overview: show data since 2000 instead of 5

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#1412]
shouldn't there be more years?

https://oodikone.cs.helsinki.fi/study-programme/520080

![image](https://user-images.githubusercontent.com/40692959/64328829-d9784680-cfd6-11e9-8e37-17543ff50bc9.png)

**Comment by cxcorp** [comment]
needs more info; backend is currently coded to calculate only 5 years back
