### ISSUE TITLE
Old study programmes' course credits mappings broken

### ISSUE THREAD

**Issue by cxcorp** [UniversityOfHelsinkiCS/oodikone#1471]
For new study programmes, the study programme to faculty mapping is simple, e.g. KH500_050 <-> 500_K050 or something. However, for old programmes the mapping is not easily possible. E.g. see study programme overview's Yearly productivity table for 520080.

Probably wontfix -mluukkai

yes, just hide all except the number of students graduated

**Comment by esakemp** [comment]
this is actually done already ages a go.
![image](https://user-images.githubusercontent.com/40692959/82309880-5e23bd00-99cc-11ea-8809-f47759d0c3cd.png)

**Comment by esakemp** [comment]
and it seems to be **impossible** to map providercodes to old programmes
