### ISSUE TITLE
Optimize frontend typing

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone#1559]
Our site is slow on frontend.
For example if looking at kasvatustieteen kandi, then writing the name of a custom filter being saved, or writing to the fields of filters, or changing the courses of population minimum students field is extremely slow. You can input only one character per second as the whole page seems to rerender on each character you type in to any textbox.

Figure out why this happens and fix it.

- [x] Population statistics
- [ ] Maybe some other pages?

**Comment by esakemp** [comment]
since state changes with each keystroke it is going to cause a re-render. To fix this simply just wait for user to stop typing and then change the state.
