### ISSUE TITLE
usage statistics timestamps

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#1581]
Why all requests of a user seem to be getting the same timestamp?

![image](https://user-images.githubusercontent.com/523235/66654202-6059b800-ec42-11e9-8197-76e40b794713.png)

**Comment by cxcorp** [comment]
![image](https://user-images.githubusercontent.com/21111572/67377625-a3931f80-f58e-11e9-9abf-b6966ebdf617.png)
