### ISSUE TITLE
Course stats numbers weird again

### ISSUE THREAD

**Issue by Rochet2** [UniversityOfHelsinkiCS/oodikone#1614]
- When using test data
- when going to 
http://localhost:8081/coursestatistics?courseCodes=%5B%22TKT10002%22%5D&cs_tab=0&separate=false&unifyOpenUniCourses=true
- and using time range 2014-15 to 2016-17
- and filter by tietojenkäsittelytieteen kandiohjelma
- All count is 107, Tietojenkäsittelytieteen kandiohjelma count is 79, but excluded count is 48.
- Shouldnt excluded = all - tkt_kandi?
- Additionally when selecting exclude as comparison group and looking at the data tables we can see that none of the tables have 48 students. They are missing around 10 students.
- Shouldnt there be at LEAST 48 attempts or students as a sum of the years? and additionally some more for fails and retries.

Below you see the counts and the data table.

![image](https://user-images.githubusercontent.com/468816/67312198-9718b380-f509-11e9-904f-f9044674b73f.png)

![image](https://user-images.githubusercontent.com/468816/67312154-836d4d00-f509-11e9-9536-e05433f6fb22.png)

**Comment by esakemp** [comment]
dropdown values are messed up because student can belong to multiple programmes (started in one programme and later changed to something else)

**Comment by Rochet2** [comment]
@esakemp that should be fixed previously for all of the programmes.
Each programme should have a student only once (even in the count), but one student can be in multiple programmes.
However it seems that "excluded" is coded differently and does not have unique studentnumbers or count.
