### ISSUE TITLE
transfers table is not minttu

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#1766]
run below query to get the non minttu ratio

`SELECT COUNT(DISTINCT concat("studentnumber", "transferdate")) as "acual", COUNT(*) as "haha",
COUNT(*) - COUNT(DISTINCT concat("studentnumber", "transferdate")) as "extras", COUNT(*)::float / COUNT(DISTINCT concat("studentnumber", "transferdate"))::float as "extras per acual"
FROM "transfers";`

**Comment by cxcorp** [comment]
Fixed by cacef1b415eceb4945085e7d298d57df26376268
