### ISSUE TITLE
Course statistics breaks when choosing multiple courses, going back, then choosing single course and clicking course

### ISSUE THREAD

**Issue by cxcorp** [UniversityOfHelsinkiCS/oodikone#1794]
https://toska.cs.helsinki.fi/sentry/oodifront/issues/1848/

1. Go to staging and choose Course statistics
2. Search for "johdatus tietojenkäsittelytieteeseen"
3. Choose both A582102 and AYTKT10001
4. Click on "Avoin yo: Johdatus tietojenkäsittelytieteeseen A582102"
5. Press "Back" on browser, notice you're back on an empty /coursestatistics but with the old search results
6. Now choose for AYTKT10001 only
7. Notice that it puts you on the Faculty statistics page that looks a bit bare
8. Click on Course tab
9. Explode

**Comment by esakemp** [comment]
faculty view is bare because anon data doesn't have faculty codes
