### ISSUE TITLE
SIS MIGRATION (DB)

### ISSUE THREAD

**Issue by woltsu** [UniversityOfHelsinkiCS/oodikone#1853]
- [x] course https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1854

- [x] course_providers https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1859
- [x] course_types https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1859

- [x] credit https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866

- [x] credit_teachers https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866

- [x] credit_types https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1861

- [x] element_details https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866

- [x] organization https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1851

- [x] providers (merged to organizations)
- [x] semester_enrollments https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1861

- [x] semesters https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1861

- [x] student https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1861
- [x] studyright https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866
- [x] studyright_elements https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866
- [x] studyright_extents https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1866
- [x] teacher https://github.com/UniversityOfHelsinkiCS/oodikone/pull/1861

- [ ] transfers

**Comment by esakemp** [comment]
transfers possibly blocked for a while due to the way SIS handles programme changes

**Comment by esakemp** [comment]
new ticket #1935 for transfers
