### ISSUE TITLE
[ Trends-CDS] Add eläinlääkis + lääkis lisensiaatti into tavoite graphs with 6 year target time

### ISSUE THREAD

**Issue by woltsu** [UniversityOfHelsinkiCS/oodikone#2032]
"joten "3v tahdissa" -> "tavoiteajassa" ja "4v tahdissa" -> "tavoiteajassa + 1""
"ohjelmat löytyy jonku maisterikoodin alta"
t. Joona

**Comment by anterogradinen** [comment]
lääketieteen kandiopiskelijoiden osalta "graduated" tulisi opintojakson "MED-1000 Myönnetty lääketieteen kandidaatin arvo" kirjaamiseksi hyväksytyksi

**Comment by anterogradinen** [comment]
vastaava tiketti: https://github.com/UniversityOfHelsinkiCS/oodikone/issues/2688
