### ISSUE TITLE
population filters: graduation filter bug

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#2216]
in the linked population using graduation filter shows student 014175507. This student has not graduated from this programme. Instead they changed to new programme and graduated from there.

https://oodikone.cs.helsinki.fi/populations?months=23&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22520080%22%7D&year=2018

**Comment by joonashak** [comment]
Fixing this issue appears to require some backend work, as well. Will not be fixed before old filters are deprecated.
