### ISSUE TITLE
enrollmenttype 3 in SIS

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#2239]
is SIS looks like

eg student 014828236

![image](https://user-images.githubusercontent.com/523235/95852899-36f3d080-0d5d-11eb-9d3b-f641c82deb74.png)

should be treated simillarly as the case with no enrolment info at all

```
if (value === 'ATTENDING') return 1
if (value === 'NONATTENDING') return 2

return "ei mitään ilmoittautumistietoa"
```

**Comment by Jakousa** [comment]
No such thing as enrollment or enrolment in sis data. Needs more info.

**Comment by Jakousa** [comment]
Based on
https://github.com/UniversityOfHelsinkiCS/oodikone/blob/56aa541ac305705dbed41b0599d4141ce7e0dc8d/services/sis-updater-worker/src/updater/mapper.js#L169

And info from term registrations of 014828236 the possible types are ATTENDING, NONATTENDING and MISSING, whatever the numbers were in the old world. You need to fix your updater.
