### ISSUE TITLE
Add a reasonable way to clear table filters

### ISSUE THREAD

**Issue by joonashak** [UniversityOfHelsinkiCS/oodikone#2322]
Applies to population stats / courses of population and similar tables. Possibly to `SortableTable` as well, so have fun.

<img width="1419" alt="Screenshot 2020-08-31 at 18 56 55" src="https://user-images.githubusercontent.com/18666321/91740492-08aa9f00-ebbc-11ea-9ecb-a4b7329bbcf8.png">

**Comment by vaahtokarkki** [comment]
Apparently fixed, pls reopen if some (sortable)table still missing this fix.
