### ISSUE TITLE
Run DOOM in oodikone-staging.cs.helsinki.fi/doom VOL.2

### ISSUE THREAD

**Issue by esakemp** [UniversityOfHelsinkiCS/oodikone#2349]
Pull mattipaksula/ws-doom and share

**Comment by sasumaki** [comment]
Please make it public so I dont need to use vpn

**Comment by mluukkai** [comment]
vmp

**Comment by esakemp** [comment]
Not vmp

**Comment by mluukkai** [comment]
pe*kele

**Comment by esakemp** [comment]
Ei kiroilla

**Comment by sasumaki** [comment]
#1539  I think this issue is related so it should probably be re-opened.

**Comment by woltsu** [comment]
Any updates on this? Our whole deployment pipeline is literally frozen due to this issue...

**Comment by sasumaki** [comment]
I think they fired @esakemp who was supposed to implement this..

**Comment by esakemp** [comment]
Don't believe @sasumaki

**Comment by sasumaki** [comment]
doom.toska.dev
