### ISSUE TITLE
courses of population does not work when filters applied

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2420]
TKT kandi 2017

Vanha

![image](https://user-images.githubusercontent.com/523235/99984680-0e2c1580-2db6-11eb-92b7-71cae9da6464.png)

uusi

![image](https://user-images.githubusercontent.com/523235/99984934-59debf00-2db6-11eb-877d-64506e908865.png)

**Comment by saarasat** [comment]
Has been magically fixed at some point, probably when filters where re-done
