### ISSUE TITLE
course statistics: the last term missing

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2477]
![image](https://user-images.githubusercontent.com/523235/102468411-26601f00-405a-11eb-9c55-d1c5bf685707.png)

but eg. ohtuprojekti has also later attainments 

![image](https://user-images.githubusercontent.com/523235/102468559-56a7bd80-405a-11eb-91cc-020a71526dba.png)

**Comment by Sendouc** [comment]
Checked the frontend logic and it seems correct. I think the problem is that `max_attainment_date` is wrong in the database.
