### ISSUE TITLE
Investigate credit foreign key error while updating.

### ISSUE THREAD

**Issue by Darake** [UniversityOfHelsinkiCS/oodikone#2484]
Edit: 16 attainments found with `module_group_id='hy-SM-125118355'` but no modules are found with that group_id. According to the date and student number the module missing might be `Luonnontieteiden kandidaatti (00345)`.

Errors happen when trying to insert a credit into table but no course with course_id found.
![102523120-cf7d3880-409f-11eb-8ee9-7af26e5419e4](https://user-images.githubusercontent.com/33695190/102525116-85498680-40a2-11eb-87fe-34133b3df0ac.png)

**Comment by vaahtokarkki** [comment]
Fix'd in Sisu, now can be found from importer db
![image](https://user-images.githubusercontent.com/12064374/104280187-31b93580-54b4-11eb-91bd-0bee7d1d1c1c.png)
