### ISSUE TITLE
course/custom population: should be possible to see courses with less than n participants (was possible before)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2494]
eg tried to see Ohjelmistotuotanto but that is not listed since it has only handful of participants

![image](https://user-images.githubusercontent.com/523235/103544783-48a2cb00-4ea9-11eb-86fa-b4e376c3dbf4.png)

**Comment by otahontas** [comment]
adding this to oodikone 2 so we can groom at some point
