### ISSUE TITLE
studyrights formed incorrectly in some cases

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2603]
compare below three. the first is fucked (and might cause #2584):

014739396

![image](https://user-images.githubusercontent.com/523235/107798657-22ecc980-6d65-11eb-8fd2-c3fb7eed5648.png)

014689116

![image](https://user-images.githubusercontent.com/523235/107798729-35ff9980-6d65-11eb-9cc9-7da261116e44.png)

014837010

![image](https://user-images.githubusercontent.com/523235/107798577-03ee3780-6d65-11eb-9863-a75e10191a09.png)

**Comment by otahontas** [comment]
these are now formed correctly
