### ISSUE TITLE
Add updater endpoint to update every student in programme x / year y

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2697]
related to #2694, make it possible to update stuff directly in updater scheduler

**Comment by otahontas** [comment]
reasoning behind: our current logic relies on backend, but would be better if updater was able to figure out studentnumbers to update directly from importer tables

**Comment by joonashak** [comment]
@otahontas this is already implemented, is it not? Closing for the time being.
