### ISSUE TITLE
Akvaattisten tieteiden moduulin kaikki kurssit eivät näy courses of populationissa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2698]
ympäristötieteen kandin kurssit

Näyttäisi siltä, että asia on osittain korjaantunut itsestään. Lisäksi nyt pienten muutoksen myötä updaterissa ENV -315 on ilmestynyt  moduuliin - ainakin lokaalisti (OS) Odottaa tuoantoa ja programme moduulien päivitystä.

![image](https://user-images.githubusercontent.com/523235/111160824-27deac00-85a3-11eb-8624-544841ee8b48.png)

--
29.8.22
Johtuu ehkä siitä, että kurssi on osa useampaa moduulia (AS)

**Comment by Sendouc** [comment]
-> back ei palauta coursestatistics kyseisille kursseille (router.post('/v2/populationstatistics/courses’)
-> hypoteesi: bäkkäri ei palauta kursseja koska kukaan opiskelija ei ole suorittanut niitä

Tämä vaikuttaa mahdolliselta koska mitään kurssia ei näy jossa olisi 0 opiskelijaa ja eri vuosikurssit näyttävät eri kursseja. Tulevaisuuden parannusehdotus olisi mahdollisesti ehkä että näytetään kurssit joissa 0 opiskelijaa (mandatoryCourses listaa kun verrataan courseStatistics niin vaikka jotain kurssia ei löydy courseStatistics niin lisätään se silti 0:lla opiskelijalla)
