### ISSUE TITLE
issues in bachelor studyrights (prblms in oodi-oodikone)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2702]
```
KH40_004
   2017    oodi only 1 both 96
   011531500
```

Should _not_ be in oodi-oodikone since is not present at current term. 

```
KH50_001
   2020    sis only 1 both 426
   013866367
```

Should be in oodi-oodikone since has reactivated the studyright. Sis-oodikone is here right

```
KH50_005
   2020    sis only 1 both 680
   014617913
```

Should be in oodi-oodikone since has registered absent this term

```
KH55_001
   2019    sis only 2 both 165
   015160142
```

no idea why oodi-oodikone does not show this

**Comment by otahontas** [comment]
011531500 is actually ok, since absents are also included in populations be default

**Comment by otahontas** [comment]
not fixing, since these are correct in sis
