### ISSUE TITLE
duplicates in studyrights

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2706]
eg:
015186210

others:
014823053
015110613
011632548

find out:

SELECT studentnumber, code, count(code) as cnt FROM "studyright_elements" 
WHERE code like 'KH%'  GROUP BY studentnumber, code ORDER BY cnt DESC LIMIT 10000

**Comment by otahontas** [comment]
happens also in masters, e.g. 013066769
<img width="916" alt="image" src="https://user-images.githubusercontent.com/43019238/112799408-f839a480-9076-11eb-9d6e-a526eacac7c2.png">
