### ISSUE TITLE
Overview for specializing education (erikoistumiskoulutukset)

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#2796]
Miten saada Overview-näkymä koulutuksille, joilta puuttuu koulutusohjelmastatus? Esim. 
-Kliinisen mielenterveyspsykologian erikoispsykologikoulutus
-Neuropsykologian erikoispsykologikoulutus

Esim.
![image](https://user-images.githubusercontent.com/72501421/114837975-eaa54e00-9ddc-11eb-9023-6b845f292dcf.png)

**Comment by otahontas** [comment]
Näkyvät adminille, mutta oikeuksia ei pysty vielä antamaan. Fix oikeuksien antaminen

Related: #2850, #3065
