### ISSUE TITLE
Fix program crashing when toggling course module visibility states

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2842]
To reproduce:
- go to degree courses page for some study module
- randomly click "set visibility" for different course modules
- frontend crashes

**Comment by otahontas** [comment]
Sentry error: Error [ERR_HTTP_HEADERS_SENT] POST|/v3/programme_modules/:programmecode/ probably related to this

**Comment by saarasat** [comment]
Backend returns an empty list now instead of 400 if no modules are found. Also some additional checking has been done in the front-end. Should be fixed, at least I have not been able to reproduce this error anymore.
