### ISSUE TITLE
014957356 farmaseutin koulutusohjelma näkyy peruttuna

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2845]
dunnop why, ei ole phase2:sta

**Comment by otahontas** [comment]
taitaa olla alunperin fakap oodissa, koska opiskelijalla näkyy farmasetuin koulutusohjelma tuplana.

**Comment by otahontas** [comment]
https://jira.it.helsinki.fi/browse/DOO-4485
