### ISSUE TITLE
014467710 ei pitäsi näkyä Sosiaalitieteiden maisteriohjelma:ssa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2854]
Ympäristömuutoksen ja globaalin kestävyyden maisteriohjelma on acual

![image](https://user-images.githubusercontent.com/523235/116585437-136f2c80-a921-11eb-85cc-29d72d23dfb2.png)

**Comment by otahontas** [comment]
ok in production
