### ISSUE TITLE
Upgrade updater to newer node 

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2856]
To node ~~14, or even node 16~~. 18 

There will probably be some bugs with sequelize and knex major version updates. See e.g. #2808 
also issue #3503

- [x] Scheduler
- [x] Worker
- [x] Also into production

**Comment by ShootingStar91** [comment]
Related [#3503](https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3503)
