### ISSUE TITLE
010956351 maisterivalinta canceled sis-oodikoneessa, mutta läsnä oodi-oodikonessa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2859]
phase 2 kyllä löytyy eli updater-issue?

**Comment by otahontas** [comment]
phase 2 on ok, mutta uusin studyright on passive, sis-kälissä näin:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/43019238/116851994-30934c00-abfc-11eb-8e44-a2dc8c372715.png">

**Comment by otahontas** [comment]
samaa sarjaa kuin #2830

**Comment by otahontas** [comment]
eli case on:
- maisterivalinta näkyy, mutta on canceled, koska sisussa studyrightilta puuttuu term registration kokonaan. Toisessa tutkinnossa kuitenkin on term registration ok

**Comment by otahontas** [comment]
https://jira.it.helsinki.fi/browse/DOO-4483
