### ISSUE TITLE
014591314 näkyy kahdessa vuosikerrassa

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2860]
![image](https://user-images.githubusercontent.com/523235/116809744-45160c80-ab48-11eb-81ef-0966c3eb813d.png)

oodi-oodikone

![image](https://user-images.githubusercontent.com/523235/116809761-64ad3500-ab48-11eb-90f4-6f5db1421b4f.png)

**Comment by otahontas** [comment]
https://jira.it.helsinki.fi/browse/DOO-4479
