### ISSUE TITLE
starting date in KH60_001

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2861]
014829031 is in two populations currently, also suspicious in oodi-oodikone

**Comment by otahontas** [comment]
looks like bug in oodidata: msc study start date is "2017-04-07T21:00:00.000Z" --> obviously wrong, since student has graduated 5.4.2021. This causes sisu to show student in correct bsc+msc -studyright, but also in just msc studyright.

**Comment by otahontas** [comment]
https://jira.it.helsinki.fi/browse/DOO-4478
