### ISSUE TITLE
varhaiskasv kandi, valmistuminen näkyy sisussa, puuttuu importerista (su 2.5. klo 1347)

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#2864]
![image](https://user-images.githubusercontent.com/523235/117116625-40936300-ad97-11eb-989c-fa86dc6dcced.png)

014750427
014739590
014849105
014848627
014811706
014830114
014786132
011488048
012740617
014451234
014739590
014848627
014849105
011488048
014624977
014659133
014720169
014721825
012740617
014786132
014451234
014323074
014366086
014528934
014708699
014711262
014726105
014728983
014731909

**Comment by mluukkai** [comment]
014811706
014830114

**Comment by Jakousa** [comment]
![Screenshot 2021-05-03 at 13 30 18](https://user-images.githubusercontent.com/6400208/116871976-cc817f80-ac1d-11eb-9abf-4976ccc2a2fb.png)

![Screenshot 2021-05-03 at 14 45 24](https://user-images.githubusercontent.com/6400208/116872250-3e59c900-ac1e-11eb-8aec-dca2ae50e39f.png)


Näyttäisi siltä että opiskelijoilla "ei ole suoritettuja tutkintoja" vaikka sellaisia tulisi olla. Tallessa näyttäisi olevan samat kuin mitä api antaa meille.
