### ISSUE TITLE
Fix student studyright change and previous studyright not showing at all in sis-oodikone

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2904]
Not sure if sis data problem or problem in updater. Details:
- Geologia 1970 - 1997 doesn't show in sis-oodikone, but shows in sis käl
- Physics 1987 - 2019, then tkt old 2019 (valintalautakunnan päätös), then tkt new 2020 -> shows in oodi-oodikone, but not in sis. 

Sis käl shows some information about valintalautakuntachange, check if transfer is calculated correctly in sis updater

**Comment by mluukkai** [comment]
dunno what student
