### ISSUE TITLE
Studyrights and credit graph weird for student

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2935]
012603026

credit graph shows minus in SIS
![image](https://user-images.githubusercontent.com/43019238/119139909-39817b80-ba4c-11eb-9011-c19ca20641ea.png)

studyrights look a bit weird compared to oodi, but on the other shows logical path in SIS. However, kemian koulutusohjelma is missing from sis

**Comment by saarasat** [comment]
Kemian koulutusohjelma is now there and credit totals have been fixed
