### ISSUE TITLE
Check that gender codes match in frontend, backend and updater

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2959]
Updater uses 4 gender codes based on what oodi used to have. Check that frontend and backend use these too

**Comment by saarasat** [comment]
Actually yes, works correctly on all levels. Now added the gender Other to frontend studyprogramme throughtput tables as well.

Here is how the mapping goes from updater to backend to frontend:
1. **updater (sis)** urn:code:gender:male - **backend**: 1 - **frontend**: male (value 1)
2. **updater (sis)** urn:code:gender:female - **backend**: 2 - **frontend**: female (value 2)
3. **updater (sis)** urn:code:gender:other - **backend**: 3 (62 persons) - **frontend**: Other (value 3) 
4. **updater (sis)** NULL - **backend**: 0 (39 persons) - **frontend**:  Unknown (value 0)

The Unknown field is basically consisting of random test persons and organisations also present in Sisu and some data from 80's and 90's. They are not presented in frontend data, and their creditcounts are 0, except for one student who has 3 credits of an open university course.
