### ISSUE TITLE
Find out what to do with course_providers without organisation

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#2973]
"entity":{"composite":"otm-e833df18-8d40-4f61-966c-a6b8e72f3bec-
tuni-org-1010000006","coursecode":"otm-e833df18-8d40-4f61-966c-a6b8e72f3bec","organizationcode":"tuni-org-1010000006"}}}                                                                                                                                                                                                

updater fails to create course_provider for this, since tuni-org-1010000006 isn't an organization we have in our data

**Comment by vaahtokarkki** [comment]
![image](https://user-images.githubusercontent.com/12064374/155942392-1562086a-3dc0-434e-a3ce-bf99ca133277.png)
