### ISSUE TITLE
Check problem with kemian kandiohjelma

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3053]
"Yritän kerätä dataa kemian kandiohjelman opiskelijoiden suorituksista eri kursseilla viime vuosina. Törmäsin seuraavaan ihmeellisyyteen

 

Kurssi: KEK202

Lukuvuosi: 2017-18

Kemian kandiohjelman opiskelijoiden suorituksia 8 / hylättyjä 7

 

Mutta kun klikkaan lukuvuoden tarkempia tietoja (Population of course Yhdisteiden rakenteiden selvittäminen 2017-2018) niin siellä näkyykin vain 2 kpl kemian kandiohjelman opiskelijoita. Mistähän tässä on kyse?"

**Comment by Petrimus** [comment]
Nämä kaksi näkymää toimivat eri logiikalla. Course statistics rajaa opiskelijoita sen mukaan, mikä on heidän viimeisin studyrights_elements, kun taas population of course näyttää opiskelijan sen studyrights_elementsin mukaan, mikä oli aktiivinen kurssin suoritusajankohtana (snapshot).
