### ISSUE TITLE
Check how open uni courses without AYcode are handled in course statistics

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3070]
From autumn 2021 open university course will not have AY-start in code names. We currently rely on this to check if course is from open university, which won't work anymore.

Investigate how to check course provider from attainments / course units. See KORI / ORI api for more details.

**Comment by Petrimus** [comment]
This is sorted out and tested in course statistics. Seems to work, but there more places to propagate this solution.
