### ISSUE TITLE
Update tietosuojaseloste

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3103]
- [x] remove old
- [x] link to UH general seloste (linki in file tietosuojaseloste.md)
- [x] same to sp-registry

**Comment by anterogradinen** [comment]
"Opintohallinnon Oodi-järjestelmästä on siirrytty Sisu-järjestelmään.
 
Tämän vuoksi Oodikone-järjestelmän tietosuojaselosta tulee päivittää. Varmistaisin, mitä uuteen selosteeseen pitäisi tulla ja miten kuvausta pitää päivittää suhteessa sisuun? Riittääkö vaan, että kuvauksesta Oodi-järjestelmä korvataan Sisulla?
 
Liitteenä on nykyinen tietosuojaseloste vuodelta 2018."

---

"Hei!

Kiitos! Tämä oodikone on ilmeisesti vain henkilöstön käytössä? Jos näin on ja kun tuossa vanhassa ilmoituksessa ei hirveästi sisältöä ollut niin sanoisin, että luovutaan siitä ja lisätään tänne yleiseen tietosuojailmoitukseen Opiskelijoiden henkilötietojen käsittely kohtaan ”Miksi käsittelemme henkilötietoja” käyttötarkoituksiin: 
-	Tilaistointi
-	Opiskelijoiden opiskelumenestyksen ja opintojen etenemisen seuraaminen 

Tietosuoja-asetus ei nimittäin edellytä tuollaisten ”rekisteriselosteiden” ylläpitoa tai antamista (ja niitä yritämme turhia karsia) vaan että käsittelytoimet on kirjattu ns. käsittelytoimiselosteeseen (sisäinen dokumentti, ei julkaista, tarkistan että tämä on siellä mainittu) ja informointi voidaan toteuttaa vapaamuotoisesti, pääasia että se on ytimekästä ja selkeää. Olette hyvin kuvanneet Oodikonetta myös näillä sivuilla: https://blogs.helsinki.fi/oodikone/ , https://studies.helsinki.fi/ohjeet/artikkeli/opintojen-seuranta joten tietosuojailmoitusmielessä mielestäni nuo pienet lisäykset tuohon yleiseen tietosuojailmoitukseen olisivat riittäviä. 

Mitä mieltä olette? 

Lotta"
