### ISSUE TITLE
Hyv.grade showing with red circle

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3207]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/43019238/133498163-976912eb-4d40-454e-a781-cf5602c4c776.png">

Hyv. should be accepted, not failed, whats going on with 014666676

**Comment by saarasat** [comment]
Seems to be a secondary completion and that is why it was mapped with credit type code 7 (Improved) by updater. So the problem seems to be in the backend, it shouldn't map improved as failed for these cases.
