### ISSUE TITLE
Fix study guidance group crashing when fetching population without rights for some students

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3208]
https://oodikone.helsinki.fi/studyguidancegroups/otm-75c82025-60f3-4390-be1e-9586d1e3567a

**Comment by otahontas** [comment]
This  is a study guidance group for user _mehaveri_, name SOTE-RYHMÄ. Problem is that group contains only one student and user doesn't have rights to access that students information. Check what to do, access to student / error message to user?
