### ISSUE TITLE
Write CreditAccumulationGraphHighCharts without the component class -structure

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3216]
There are multiple legacy-methods that are not recommended to be used anymore relating to the [mounting of the component](https://reactjs.org/docs/react-component.html). Might fix the graph not showing any data on the first load: 
![Screenshot from 2021-09-21 18-05-16](https://user-images.githubusercontent.com/43036333/134196448-7b325c55-744d-4f76-8931-828912249e8b.png)

After updating some parameters:
![Screenshot from 2021-09-21 18-04-22](https://user-images.githubusercontent.com/43036333/134196368-bc2bc401-336c-448a-b811-1fafd5a14151.png)

**Comment by dogamak** [comment]
Resolved in https://github.com/UniversityOfHelsinkiCS/oodikone/commit/0ce965abe3b14e455fd872b09062af1e1042143a.
