### ISSUE TITLE
[Trends ]Compare relative trends: master’s degree programmes

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3273]
Toiveena, että opinto-oikeuden kestoa käytettäisiin myös Trendseissä maisteriohjelmien opiskelutahtien monitoroimiseen: https://oodikone.helsinki.fi/trends/relative

Toive koulutusohjelmista: "Kyllä, on toiveena, että tätä tietoa käytettäisiin myös Trendseissä maisteriohjelmien opiskelutahtien monitoroimiseen."

Kytkeytyy tikettiin  amount of days spent: studyright #3272: https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3272

**Comment by otahontas** [comment]
Let's do #3178 first
