### ISSUE TITLE
Fix courses of population not showing all courses inside study guidance groups

### ISSUE THREAD

**Issue by otahontas** [UniversityOfHelsinkiCS/oodikone#3309]
Courses are filtered too early (before sending to single study guidance group). Pass all courses instead.

EDIT: above is acually not the reason, something more complex happening

**Comment by SNurmivaara** [comment]
Some of the problems were fixed with a recent change to courses of population, but there are still some unresolved issues that are hard to pinpoint. This ticket is a bit too vague, so closing for now and creating a new one with a more concrete bug report.
