### ISSUE TITLE
[Studyprogramme overview] Adjust mean and median time calculations 

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3331]
This is done in Rapo (raportit toiminnasta ja taloudesta): 

ALEMPI:
Tämä analyysi on toteutettu laskemalla tutkintoon käytetyt läsnäololukukaudet sekä ne lukukaudet, joina opiskelija on ollut kirjoiltapoistettuna. Tätä verrataan alemman korkeakoulututkinnon tavoiteaikaan, joka on kuusi lukukautta. Laskennassa ei ole huomioitu niitä poissaololukukausia, jotka kuluttavat tavoiteaikaa

YLEMPI:
Tämä analyysi on toteutettu laskemalla tutkintoon käytetyt läsnäololukukaudet ja vertaamalla niitä ylemmän korkeakoulututkinnon tavoiteaikaan, joka on pääsääntöisesti neljä lukukautta, tai alemman ja ylemmän korkeakoulututkinnon yhteiseen tavoiteaikaan, joka on pääsääntöisesti kymmenen lukukautta.
Poikkeuksena tähän ovat psykologian maisterin (5 lukukautta tai 11 lukukautta), eläinlääketieteen lisensiaatin (12 lukukautta), lääketieteen lisensiaatin (12 lukukautta) ja hammaslääketieteen lisensiaatin (10 lukukautta) tutkinnot (tavoiteaika suluissa). Laskennassa ei ole huomioitu niitä poissaololukukausia, jotka kuluttavat tavoiteaikaa.

**Comment by sinikala** [comment]
This is already done in faculty view
