### ISSUE TITLE
Grafana: exclude users kmitja and ohj_tosk from stats

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3408]
![image](https://user-images.githubusercontent.com/72501421/152097996-147be158-a6d7-433e-80a4-acd0ec2f0c0e.png)

**Comment by anterogradinen** [comment]
![image](https://user-images.githubusercontent.com/72501421/152098638-3fcabb6f-75b3-46a9-83b3-16ae70c2e866.png)

**Comment by saarasat** [comment]
This also seems to work now, those users no longer show in grafana stats
