### ISSUE TITLE
Population statistics: check that transferred to -filter works for all students

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3409]
For instance student: 014696659 has transferred to programme KH40_003 from 420092-ba (class of KH40_003, year 2017-2018). But when choosing "Not transferred" in populations, the student still pops in the list 

![image](https://user-images.githubusercontent.com/43036333/152124686-e7c299c0-baa8-4724-8482-33aa23da29d2.png)

**Comment by vaahtokarkki** [comment]
Works already
