### ISSUE TITLE
course statistics: PED511 gives error after fetchin stats

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3414]
Ei toimi: https://oodikone.helsinki.fi/coursestatistics?courseCodes=%5B%22PED511%22%5D&cs_tab=0&separate=false&unifyOpenUniCourses=false

Lataa ja tulokset näkyy 1s. sitten menee rikki

Toimii: https://oodikone.helsinki.fi/coursestatistics?courseCodes=%5B%22PED590%22%5D&cs_tab=0&separate=false&unifyOpenUniCourses=false

**Comment by saarasat** [comment]
Both of these seem to work now.
Probably been fixed when working on other tickets.
