### ISSUE TITLE
Teachers: produced credits per teaching hours

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3435]
https://oodikone.helsinki.fi/teachers?t_tab=0 sivulle uusi näkymä.

![image](https://user-images.githubusercontent.com/72501421/155125630-e26ebdd1-e3d1-45e0-b3d5-2d416ef36d2e.png)

Sisusta saa opetuksen toteutuksen tuntitiedot (esim. https://sis-helsinki.funidata.fi/teacher/role/staff/teaching/course-unit-realisations/view/otm-206daf3d-d415-465a-bf51-d0054ab9073a/information/structure)
![image](https://user-images.githubusercontent.com/72501421/155126234-32ea6db1-0cad-449c-a94e-599b7b79774d.png)

--
Edit: Mietittävä, onko näkymä puhtaasti opettajan kaikki tuottamat opintopisteet / kaikki sisusta saatavilla olleet opetustunnit vai jotain toteutuskohtaisempaa.

**Comment by anterogradinen** [comment]
Tulisiko myös näkyviin course statistics-osioon, jolloin näkymä on kurssikohtainen (erotuksena opettajakohtaiselle)? toisaalta tähän lukuun tulee sotkemaan erilliskirjaukset tms?

**Comment by anterogradinen** [comment]
Opintohallinnon kommentteja: 
[13.14] Lönnström, Lauri S
Periaatteessa kaikki tieto löytyy, jotta voisi linkittää Optimessa olevat tuntimäärät toteutuksiin ja niiden kautta annettuihin arviointeihin. Mutta tiedot ovat sen verran hajallaan tietokannoissa, että voi olla aika raskas prosessi noita tietoja louhia ja yhdistellä. Jos siis haluaisi yhdistää juuri oikeat opintopisteet tiettyyn opetustuntimäärään ja saada jonkinlainen tuottavuuslukema per opettaja.'

[13.19] Lönnström, Lauri S
Joo, on se louhittavissa. Leealla [Leea Sokura] voisi olla aika hyvä käsitys siitä, että miten ne tiedot siellä lopulta makaa ja kuinka iso urakka olisi kaivella ja yhdistellä niitä tietoja.

**Comment by vaahtokarkki** [comment]
Path to get study events per course unit realisation:

course unit realisation --> list of studySubGroupSets --> list of studySubGroups --> list of **teacherIds**, list of studyEvents -->| list of events --> **duration**, list of **irregularTeacherIds** (empty)

Study event contains only `irregularTeacherIds` which may be empty, study sub group (attached to course unit realisation)  contains list of teachers 
![image](https://user-images.githubusercontent.com/12064374/155278642-65969331-3758-49a6-ba66-6cc7ccbe075d.png)
