### ISSUE TITLE
Study guidance group "Courses of population" doesn't show all courses

### ISSUE THREAD

**Issue by SNurmivaara** [UniversityOfHelsinkiCS/oodikone#3441]
Study guidance groups sometimes don't actually show all courses in "Courses of population". This bug happens somewhere between db -> front, but hasn't been pinpointed and is a bit fuzzy - the exact boundaries of this bug are unknown (what is dropped, where, why)

One example case is student XXXXXXXXX (ask @SNurmivaara for demo/student number) who is in study guidance group "Tietojenkäsittelytiede 2017, avoimen väylä (Matti Luukkainen)" that has "Hyl." for course TKT21009 in db. This course is dropped somewhere, as on the front it isn't anywhere (not even redux).

This problem is not simply "Don't show courses that have only failures", as course MAT22002 is exactly the same kind of course down to the credit type code, that has only fails (2 students), but is still seen in the "courses of population".

**Comment by vaahtokarkki** [comment]
The course TKT21009 can be seen when using the "Show courses as flat list". The course is probably not in the programme structure and therefore not visible in the default view.
