### ISSUE TITLE
Update at least some dependencies

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3446]
One place to start: https://github.com/UniversityOfHelsinkiCS/oodikone/security/dependabot

**Comment by SNurmivaara** [comment]
Dependabot now actually does what it's supposed, sees all our services and labels pull requests correctly.

Codebase had gotten very outdated, ran a semver safe update and manually fixed a couple of issues.

Created issue #3503 for updating knex at some point, as there is a breaking change in the next version available.

Fixed 22 security alerts🎉
