### ISSUE TITLE
study programme and study programme overview access based on IAM

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3460]
All study program councils will soon have IAM groups provide access based on groups as follows

- group member => access to population overview
- group member && in personnel ==> access to population pages

for testing: hy-mltdk-tkt-jory

One more thing:

- [x] save IAM info to user db since login_as does not work without that 
- [x] see also https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3463

**Comment by anterogradinen** [comment]
tarvitaan joku uusi jory-käyttäjäryhmärooli eikö vaan nykyisten lisäksi (courseStatistics, studyGuidanceGroups + degreeprogramme joka ei varsinaisesti ole rooli tuolla user-sivulla)? Tässä jory-roolissa näkymä vain overview-näkymän 1 ja 2 tabin tietoihin (Basic information + Study tracks and student populations), muttei pääsyä populaatioihin (vuosikursseihin). Lisäksi oodikone päättelee oikeudet oikeisiin ohjelmiin iamien pohjalta, joka on toimitettu toskalle excel-listana.

Tää tarjoaa hyvä base-oikeudet kaikille joryn jäsenille (ml kojo). Toistaiseksi ei olla kuitenkaan saatu vielä keksittyä, miten saataisi kojoille kojo-oikeudet oikeisiin ohjelmiin automaattisesti, koska voi olla olla kojo ohjelmassa x ja joryn jäsen ohjelmassa y. Excel-listassa on kyllä nimettynä kojo, mutta sitä ei päivitetä.... Eli jokin määrä käsipeliä vaaditaan.

**Comment by anterogradinen** [comment]
[Koulutusohjelmien lyhenteet.xlsx](https://github.com/UniversityOfHelsinkiCS/oodikone/files/8203148/Koulutusohjelmien.lyhenteet.xlsx)

**Comment by anterogradinen** [comment]
Näkymät siis näihin
![image](https://user-images.githubusercontent.com/72501421/157177182-273fe191-c43d-4e44-bfbf-f4eaa55ac728.png)

**Comment by anterogradinen** [comment]
IAM-ryhmät valmiit

**Comment by anterogradinen** [comment]
[Koulutusohjelmien oppiaine ja johtoryhmä iam.xlsx](https://github.com/UniversityOfHelsinkiCS/oodikone/files/8519543/Koulutusohjelmien.oppiaine.ja.johtoryhma.iam.xlsx)
