### ISSUE TITLE
Overview: add 180 credits option to progress of students of the studyprogramme by start. year (table&graph)

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3464]
![image](https://user-images.githubusercontent.com/72501421/157199864-924bd92c-07af-4a36-bb64-bd6fe932e1f2.png)

Jos mahdollista, myös valmistuneet mukaan tähän kuvaajaan + taulukkoon?

Onko samaa ominaisuutta mahdollisuutta saada maisteriohjelmiin?

**Comment by saarasat** [comment]
1. Maisteriohjelmista tuo pitäisikin jo löytyä. 
2. +180 credits hyvä lisä, laitetaan tulemaan

**Comment by saarasat** [comment]
Lisäsin nyt kategoriat 180+ ja 300+, pitäisi päivittyä tuotantoon 15 minuutin sisällä.

Katsoin myös valmistuneiden lisäämisen mahdollisuutta. Nykyisiin kolumneihin valmistuneet kategoria ei oikein sovi, koska graafi ja taulukko näyttää osuuksia populaatiosta ja yksi opiskelija voi kuulua esimerkiksi sekä 180+-kategoriaan että valmistuneisiin. Kokeilin myös valmistuneiden lisäämistä omaksi kolumnikseen, mutta se taas tekee graafista vähän hankalan lukea / sekavan.   

Ainoa tapa, millä graafiin saisi valmistuneiden määrän on näin, eli omana käyränään:

![image](https://user-images.githubusercontent.com/43036333/159222802-3c09eac7-1bee-4362-be70-63c3233bdd48.png)

Mitä mieltä olet @anterogradinen, toteuttaisinko valmistuneiden määrän näin vai jätetäänkö pois?

**Comment by saarasat** [comment]
Päätettiin slackissa, että ei lisätä käyrää
