### ISSUE TITLE
for some programme (such as Yhteiskuntatieteiden maisteriohjelma) the bachelor is not shown

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3466]
it is empty for everyone

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/523235/157248207-d9e350e3-403e-44bc-b110-851eb5c1209e.png">

reason for this is the "misuse" of SISU, these students have separate kandi and maisteri (not kandimaisteri as usual)

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/523235/157248387-251a2195-300a-4636-81f6-df07e557b4e1.png">

due to this the normal logic break. do not know if we should fix this...

edit.29.8.2022
Ratkaisu vain  Soc&Kom -> bachelor

**Comment by anterogradinen** [comment]
ks. tiketti #3577
