### ISSUE TITLE
Update knex version in sis-updater-worker and -scheduler

### ISSUE THREAD

**Issue by SNurmivaara** [UniversityOfHelsinkiCS/oodikone#3503]
sis-updater-scheduler and -worker have been locked to knex version 0.20.10 because 0.20.11 onwards is a breaking change that requires changes to the codebase. No urgency as long as not deemed a security risk.

This old issue seems to give a good hint about how to approach the change https://github.com/knex/knex/issues/3704

**Comment by ShootingStar91** [comment]
Closing this, Merged with #2856
