### ISSUE TITLE
Some credits without courses or course-ids? Investigate

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3551]
duplicate of https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3688

There are some attainments coming from sisu which error at updater. Check graylog on 28.3.2022 with message: "Updater error" for more info

https://graylog.toska.cs.helsinki.fi/search?q=message%3A+%22Updater+error%22&rangetype=relative&from=68400

![image](https://user-images.githubusercontent.com/43036333/160440417-8bb844c4-e80f-445d-a3c4-3f55726f37cc.png)

One reason is that some study programmes are missing. They do exist on importer

**Comment by vaahtokarkki** [comment]
Probably the course unit for attainment is missing from importer due `documentState` being deleted or draft.
