### ISSUE TITLE
[Trends] Show credits (current/annual) as default

### ISSUE THREAD

**Issue by anterogradinen** [UniversityOfHelsinkiCS/oodikone#3563]

**Comment by anterogradinen** [comment]
![image](https://user-images.githubusercontent.com/72501421/161027089-5fc66e61-0486-42ba-a874-66fa3e84307f.png)

**Comment by anterogradinen** [comment]
Näyttää olevan defaulttina, mutta jos tämän tsekkaa vielä!

**Comment by Petrimus** [comment]
Tää on laitettu selaimen local storageen.
