### ISSUE TITLE
[Studyprogramme overview] Decide how to display the bachelor-master-linkage between these programmes

### ISSUE THREAD

**Issue by saarasat** [UniversityOfHelsinkiCS/oodikone#3577]
These programmes miss the association to a Bachelor or Master's programme in Sisu. Should these be linked artifically in Oodikone? Or leave the table empty? 

**Only one bachelor:**
KH74_001 - Yhteiskuntatieteiden kandiohjelma

**And some master's:**
MH20_002 - Kainsainvälisen liikejuridiikan maisteriohjelma
2_MH70_007 - Yhteiskuntatieteiden maisteriohjelma 2
MH40_004 - Master's Programme in Russian Studies
MH30_001 - Lääketieteen koulutusohjelma
MH70_003 - Globaalin politiikan ja viestinnän maisteriohjelma
MH50_014 - Nordic Master Programme in Environmental Changes at Higher Latitudes
MH70_007 - Yhteiskuntatieteiden maisteriohjelma
2_MH40_002 - Kielten maisteriohjelma 2
MH30_003 - Hammaslääketieteen koulutusohjelma
MH40_011 - Kulttuurienvälisen vuorovaikutuksen maisteriohjelma
MH20_003 - Globaalia hallintoa koskevan oikeuden maisteriohjelma
MH70_005 - Nyky-yhteiskunnan tutkimuksen maisteriohjelma
MH70_010 - International Masters in Economy, State & Society
MH60_002 - Muuttuvan kasvatuksen ja koulutuksen maisteriohjelma
MH80_008 - Erasmus-Mundus Master's Programme in Plant Breeding
MH30_002 - Translationaalisen lääketieteen maisteriohjelma
MH70_006 - Euroopan ja pohjoismaiden tutkimuksen maisteriohjelma (European and Nordic Studies)

**Comment by anterogradinen** [comment]
will be fixed in 3466
