### ISSUE TITLE
Layout error: filters look strange

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/oodikone#3578]
plz see the attached picture (using firefox on laptop)
![2022-04-04_OK_layout_error](https://user-images.githubusercontent.com/43775188/161547783-1fb4fd35-90a3-4535-9a49-446b92bb8c0e.JPG)

**Comment by anterogradinen** [comment]
Tiketti 3564 liittyy kanssa tähän https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3564
