### ISSUE TITLE
[population statistics - courses] eliminate extra requests to courses endpoint

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3607]
see eg

https://oodikone.helsinki.fi/populations?months=33&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22MH50_010%22%7D&tag&year=2019

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/523235/163155067-23d0add5-c4ed-43f5-9658-c18f26cb7d38.png">

**Comment by vaahtokarkki** [comment]
Resolved in #3610
