### ISSUE TITLE
[study guidance groups - students] table fakd

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3677]
table is fakd, scrolling does not work and when name switched visible something weird happens (students lists works in study programme)

<img width="1483" alt="image" src="https://user-images.githubusercontent.com/523235/168016322-e5197d39-75e5-4e20-886c-fe13480f7ea7.png">

**Comment by SNurmivaara** [comment]
I can't seem to reproduce this, assigning for now

**Comment by SNurmivaara** [comment]
If the number of students is over some number (30? 50?), pressing "Show student names" breaks the site by moving the left toolbar out of the view and stretching the table over the browser size

**Comment by SNurmivaara** [comment]
After discussing with Mitja, it seems this issue is more widespread and the scope is currently a bit vague.

![image](https://user-images.githubusercontent.com/21972902/168530376-2de15aaa-1a20-4c33-9f47-1786167db55c.png)
