### ISSUE TITLE
[student] course missing

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3688]
duplicate of https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3551

In db 

```
015304296
{
  course_code: null,
  date: 2022-05-04T00:00:00.000Z,
  passed: true,
  grade: 'Hyv.',
  credits: 4,
  isStudyModuleCredit: null,
  credittypecode: 4,
  language: 'ja'
}
```

obviously not shown by oodikone front

looks ok in sisu

<img width="1182" alt="image" src="https://user-images.githubusercontent.com/523235/168676124-8f4626cb-01f1-4e83-8334-6c877d01d638.png">

there are also other similar cases

**Comment by mluukkai** [comment]
the deleted-issue will most likely be fixed in future

<img width="957" alt="image" src="https://user-images.githubusercontent.com/523235/169667593-a5571e4e-f61f-4803-bbdb-f3462e85c86e.png">

**Comment by vaahtokarkki** [comment]
The data in Sisu will be corrected later
