### ISSUE TITLE
[study population] filtering of transferred students

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3691]
eg in https://oodikone.helsinki.fi/populations?months=58&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22KH50_005%22%7D&tag&year=2017 the following are NOT filtered by transfer filter

```
012603026
014140121
014154120
014340455
014485938
014500554
014587140
014593516
014593532
014714081
```

everyone is obviously a transferred student (and has even a transfer object in db).

perhaps has something in common with https://github.com/UniversityOfHelsinkiCS/oodikone/issues/3409

**Comment by vaahtokarkki** [comment]
Works already
