### ISSUE TITLE
[student page - hops] a graduated student has only 27% in hops

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3700]
014807781

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/523235/169666816-18c2a4be-d4c6-47b5-8b8e-fb0143e4b5d0.png">

lots of simillar cases, eg 011547400

**Comment by LeoVaris** [comment]
It has now magically changed to 100%: https://oodikone.helsinki.fi/students/014807781 ...

**Comment by vaahtokarkki** [comment]
Both seems fine
