### ISSUE TITLE
[student page - HOPS] Count also attained substitutions

### ISSUE THREAD

**Issue by vaahtokarkki** [UniversityOfHelsinkiCS/oodikone#3719]
For example https://oodikone.helsinki.fi/students/015335731
has selected AYTKT10004 but has attained TKT10004 and the attainment is not counted to HOPS progress

**Comment by ShootingStar91** [comment]
This is fixed but the updating is buggy, the student has to be individually updated by clicking the link in student stat page, it wont update correctly in the automatic updating. #4274
