### ISSUE TITLE
Non-degree credits breakdown

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3771]
Rapo has the following categories

- [x] other column for exhange students and some else
Jaottelu tehty Kurhilan kommentin perusteella:
- 2-5 non-degree
- loput other non-degree
- [x] possibilty for csv
- [x] Bring studyright associated to credit into oodikone #4298
- [x] RAPO check

<img width="688" alt="image" src="https://user-images.githubusercontent.com/523235/177114470-b2ad989e-7169-4446-b965-d409b0690f70.png">

What should be shown in oodikone?

<img width="840" alt="image" src="https://user-images.githubusercontent.com/523235/177115006-92e095d0-625d-43f4-a7bc-437c7305ce72.png">

**Comment by vaahtokarkki** [comment]
To be able to identify different non-degree studies (separate studies, open uni studies, specialisation studies etc) we need to save all study rights to sis-db and figure out how broken Oodikone is after that change.

All education types:
https://sis-helsinki-test.funidata.fi/kori/api/cached/codebooks/urn:code:education-type

**Comment by ShootingStar91** [comment]
- When diffing, focus only on years starting from 2022
- Separate non-degree into two based on some logic. Important is that vaihto-opiskelijat is in another column. Perhaps:lines 2,3,4,5 (from the rapo table above) in one, rest in another.

**Comment by ShootingStar91** [comment]
uudempi taulukko:

![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/46905824/347f39d2-cc80-4e3a-9cf6-c5a5db82aaed)
![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/46905824/7678733c-4b0e-42af-a71c-eb09a41334cf)
