### ISSUE TITLE
[study population - course filrter] crashes on MAAT

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3876]
go

https://oodikone.helsinki.fi/populations?months=50&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22KH80_001%22%7D&tag&year=2018

filter **not graduated**

filter **course** MAAT-029 Kandidaatin tutkielma

select **did not pass** from the filter

:fire:

**Comment by sinikala** [comment]
Problem appears to be wider: Generally selecting anything else than **passed** on any programme and course is likely to :fire:
