### ISSUE TITLE
[Users] Stop mocking as -button not always visible

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#3902]
Sometimes when mocking the view as an another user, 'stop mocking as' -button is not shown.

**Comment by ShootingStar91** [comment]
When this happens, taking docker containers down and re-running seems to make the problem go away. Maybe this gives some clue to what can cause it sometimes.

**Comment by outisa** [comment]
The possible reason for being not visible is that the acual_user is logged in at the same time. The same, phenomena happens perhaps when all the tests are run on the command line -> for some reason, basic user stays as logged in, and the test with user right fails as the button is not shown.

Probably this is a wanted behaviour to indicate that the user itself is logged in. Thus, I closed this issue.
