### ISSUE TITLE
[Study programme] Fix credits view when specials excluded

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#3920]
Discuss  this through when Rapo credits are checked! What is wrong and what should be done?

Too much information is shown when all the specials are excluded? Which one is wrong: table or graph?

![image](https://user-images.githubusercontent.com/43496587/191276210-0e580737-8ccd-4b53-a812-eb0d86900e45.png)

**Comment by rikurauhala** [comment]
e479738a27c5127d7d9de992b3377ce119170e78
