### ISSUE TITLE
[study population - advanced settings] statistics until unclear

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3931]
what is 00:00 and where do this end?

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/523235/192083274-01121b82-279c-401a-b876-435dbe491c58.png">

Edit. See also #3552 ,  #3465 
+ Filter does not have any effects, for example,  to gained credits -table

**Comment by outisa** [comment]
Statistics until -field removed. For the reasons see #4030
