### ISSUE TITLE
[study programme - hops filter] when hops and date of the courses filters set, number of good students grows

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3933]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/523235/192540097-fa91d02b-b21e-4e52-9eeb-15a4c443aad0.png">

propably the dates of the credit filter does not work properly when hops filter selected

--

see

https://oodikone.helsinki.fi/populations?months=14&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22KH50_005%22%7D&tag&year=2021

this can not be true

<img width="510" alt="image" src="https://user-images.githubusercontent.com/523235/192083909-717a84fb-5a01-4dc6-8f6c-46ab9731c886.png">

**Comment by outisa** [comment]
This will be solved in issue #3940
