### ISSUE TITLE
[study population - students- courses] make a course group hidable/collapsable

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#3974]
there used to be a feature that allows hiding/collapsing a group of courses, such as this

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/523235/195168687-40fa8226-7fc2-4137-8549-c0105e5e5cd9.png">

now it does not work anymore. this makes reading the table pretty hard

**Comment by outisa** [comment]
Related to Issue #3732

**Comment by ShootingStar91** [comment]
Deemed too difficult to build with the current sortabletable. For now.
