### ISSUE TITLE
[Class statistics] Advanced settings

### ISSUE THREAD

**Issue by sinikala** [UniversityOfHelsinkiCS/oodikone#4030]
Cross-check date filters (on the filter panel and adv.settings statistics until).
If both work the same, remove the one under advanced settings, as it is a duplicate functionality.

**Comment by outisa** [comment]
Both are not working as the same, BUT the adv. setting statistics function was  computing the statistics wrongly for some reason. Example: Data Science programme starting semester 21. As I chose the ending October 2021, for me there should be 0 credits but was 64. The date filters are showing correctly.  

Obviously, advanced statistic filter not working as should.
