### ISSUE TITLE
Secondary and primary programme issues

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4131]
Could they be fixed in Oodikone?

Tutkinnon myöntävä ja opiskeluoikeuden myöntävä tiedekunta eri? Onko erotettu Sisussa?
Investigate.

Esim. maatalous-metsätieteellinen -> graduated -> opiskelijoita BIO ja ENV kandiohjelmia järjestävistä tiedekunnista eivät kuuluisi olla täällä

**Comment by outisa** [comment]
maatalous-metsätieteellinen -> graduated -> opiskelijoita bio ja env eivät kuuluisi olla täällä, investigate these!

**Comment by ShootingStar91** [comment]
Closed, newer issue remains #4375
