### ISSUE TITLE
[Language center] Statistics: First version

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4154]
- [x] "By faculties" and "by semesters" tabs
- [x] "By semesters" tab coloring functionality: Add selection to change the coloring relative to other courses (total number, perhaps)
- [x] Show semester selector also in "by semesters" tab
- [x] Change numbers: enrollments and completions and the percentage (relation of enrollments and completions)
- [x] Remove "striped" mode from sortabletable when in color mode
- [x] Clean up unused data from frontend, make sure everything possible is computed in the backend
- [x] Enrollments not accepted (optional)
- [x] Check enrollment number details: are all of them valid or are there some multiplicates (or things like HOPS enrollment)? Enrollments amount exploded when the filtering of student per course was removed
- [x] Sorting by course code
- [x] Add tests
- [x] Make release
- [x] Notify customer

(old text):

All courses produced by Kielikeskus startswith KK or AYKK for open uni.
- ~Kielikeskus as study programme: selectable from overview list~ Selectable directly from the studyprogramme menu (or other if better soulition is found)
- a custom  programme courses tab view: faculty level breakdown -> where do the students come from
    - 1 version: course|total | passed | not completed |
If time in the first iteration:
    - csv: show (students) by study programme level
  
Second version: show same on studyprogramme level in the same view.

Can credit statistics and other student statistics that are visible in normal custom tab even be computed for this view?

**Comment by ShootingStar91** [comment]
Version for first meeting:

- [ ] Filter with start / end date
- [ ] Show one table with columns course name & code, and different faculties (toggle above table to show the number of not passed, completed or total)
