### ISSUE TITLE
[faculty basic tab] Credits do not (always) match

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4156]
- [ ] Credit counts for TKT are changing by every refresh (If the data is not taken from redis)
- [ ] Are transferred students always sorted into correct 'boxes'?

**Comment by ShootingStar91** [comment]
Couldn't reproduce the changing numbers issues. It is probably fixed at some point.

Transferred students is a separate issue, the number categories are looked at in a different issue, I will mention it there.
