### ISSUE TITLE
SortableTable alphabeting ordering does mistake with lower capital surnames

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4177]
Last names may sometimes begin with lowercase letter. When sorting by name column, those surnames will be last instead of their right place.

**Comment by outisa** [comment]
Did you already did this @ShootingStar91 ?

**Comment by ShootingStar91** [comment]
> Did you already fix this @ShootingStar91 ?

yes but didnt push yet because of the cicd mayhem and then i forgot. tomorrow.

**Comment by ShootingStar91** [comment]
> Fixes are already in the production and working perfectly!

not on my machine! but we'll talk about it tomorrow
