### ISSUE TITLE
[Class stats/Study programme] Oikeusnotaari

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4185]
Miten Vaasan opiskelijat lasketaan mukaan oikeusnotariin class statistiikkaan?

**Comment by valtterikantanen** [comment]
Se, opiskeleeko opiskelija Helsingissä vai Vaasassa, näkyy study track -sarakkeessa. Eli jos study trackin perusteella ei ole filtteröity niin Helsinki ja Vaasa lasketaan yhteen.
