### ISSUE TITLE
[study programme - transfer filter] kandi-maisteri should not be treated like "normal" transfer

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4204]
now those are and that is a problem

see https://oodikone.helsinki.fi/populations?months=70&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22MH50_010%22%7D&tag&year=2017

<img width="1268" alt="image" src="https://github.com/UniversityOfHelsinkiCS/oodikone/assets/523235/0b1c8e96-2f3b-400a-9fb9-925833b6e7d2">

eg KH50_005 -> MH50_010 should not be a transfer

**Comment by outisa** [comment]
This might be related to updater problem. Now the master studyprogramme is fakd up already on the updater level, I guess. Look at the students individually (from students table).
