### ISSUE TITLE
[Updater] Hops courses

### ISSUE THREAD

**Issue by outisa** [UniversityOfHelsinkiCS/oodikone#4274]
Check how hops courses are added for the student, if many students are updated at once.

I have had now cases that when I visit student page, not all courses are added to the hops (such as DIGI-A), however, updating a student 'alone' fix this. 

hard to reproduce!

edit:
let's make a script that checks which ones are updated before latest big student update and re-run update on those

**Comment by ShootingStar91** [comment]
Closing this for now. Current solution is that a cron is ran every monday at 19 and tuesday at 10, which re-schedules all the student numbers who have studyplans with updated_at earlier than the last weekend. This is reported to slack. If the tuesday's report is not 0, it means monday's update did not do the trick which is worrying. Let's keep an eye on it.
