### ISSUE TITLE
[Class statistics] Starting year filter: Check if it works correctly & add info tooltip

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4336]

**Comment by ShootingStar91** [comment]
It shows dateofuniversityenrollment (named like this in sis-db student table). This is made by updater by taking the first start date (or valid.startDate) from importer studyrights. 

This means that the filter has been partly broken since adding open uni studyrights. I don't see an obvious way to separate open uni vs acual studyrights just with the importer studyrights table. There probably is a way. But first let's talk about if the filter is even wanted.

- [ ] Talk what the desired functionality is
- [ ] Acual do it
- [ ] Add tooltip explaining what the heck it does

**Comment by valtterikantanen** [comment]
The following `education_type`s should be ignored when determining the start date:

- All urn's containing "non-degree-education"
- degree-education:specialisation-in-medicine-and-dentistry
- degree-education:specialisation-in-veterinary
