### ISSUE TITLE
[Course statistics] Total number of passed students does not match the different grades combined

### ISSUE THREAD

**Issue by valtterikantanen** [UniversityOfHelsinkiCS/oodikone#4339]
See for example [this course](https://oodikone.helsinki.fi/coursestatistics?combineSubstitutions=true&courseCodes=%5B%22TKT20016%22%5D&cs_tab=0&separate=false).

Year 2023–2024 is showing a total of 16 students who passed the course. If "show grades" toggle is on, total number of students with passed grade (1–5) is 18.

![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/91893789/d8994fcf-852d-41a6-b607-85cae9040aaa)

![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/91893789/d4c44d11-922a-4cfc-a646-dd08c11ecee3)

**Comment by rikurauhala** [comment]
Closed as duplicate, see #4611.
