### ISSUE TITLE
Course stats: Clarify UX of toggles

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4340]
Now there are 3 different kind of toggles and especially Students vs Attempts toggle doesn't even look like a toggle.

Also figure out if some of the toggles could just be removed or the entire logic simplified. Somewhat related issue: #4339 

Mostly done, but for pass rate charts this still should be somehow resolved, possibly just change the outlook of the toggle to be more toggle-like

**Comment by rikurauhala** [comment]
e4c6c5938c42b4bec70acafaea02b039f1b475c8
