### ISSUE TITLE
Enrollment date time and semester code

### ISSUE THREAD

**Issue by valtterikantanen** [UniversityOfHelsinkiCS/oodikone#4371]
See `enrollment` table from sis-db. For example enrollments with ids

```
otm-d3c424d8-21be-4eaa-bc32-7f7f909232c6
otm-5f948df2-e308-4730-a421-b4a80359da7d
```

have different semester codes (146 and 147) even though the enrollment dates are 2023-05-02 and 2023-05-31. Both are in May 2023 so the semesters should be the same.

So what does the semester code refer to? Or is the semester code the semester in which the course is organized? The following info is valid (from `semesters` table):

```
+--------------+------------------------+------------------------+
| semestercode | startdate              | enddate                |
|--------------+------------------------+------------------------|
| 146          | 2023-01-01 00:00:00+00 | 2023-08-01 00:00:00+00 |
| 147          | 2023-08-01 00:00:00+00 | 2024-01-01 00:00:00+00 |
+--------------+------------------------+------------------------+
```

**Comment by ShootingStar91** [comment]
This was correct, semesters referred to some examinations and the other was in may and other in august
