### ISSUE TITLE
[Users] speed up table: cache it somewhere. No need to update everything every time it's loaded

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4401]

**Comment by ShootingStar91** [comment]
It's sped up significantly, and reloading the view in single user page doesn't load the whole table anymore. However, it's still quite slow, something like 11 seconds. Some suggestions

- [ ] Taking roles away from user-db and only inferring them from iams in code
- [ ] having "elementdetails" (rename that shit) which is the programmes, in JSONB column in user-db instead of a join query

**Comment by valtterikantanen** [comment]
Previously Jami returned all users in its own db even though they're not all users of Oodikone. Currently loading the whole users table takes ca. 25 seconds in production if the Sisu access info is not in the cache (currently stored for 24 hours). After Sisu access info is in Jami's cache, the request only takes about 2 seconds, so I will close this as not planned.
