### ISSUE TITLE
[courses - graphs] only enrolled persons not shown

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4407]
graafit ei huomioi noita enrolled no grade ollenkaan

<img width="1081" alt="image" src="https://github.com/UniversityOfHelsinkiCS/oodikone/assets/523235/d2396057-2e86-4dda-80fe-93e2b7b44bbc">

**Comment by rikurauhala** [comment]
9d474ca61eb5ab9bfc3af6fefbe073312dce49c2
