### ISSUE TITLE
[courses - graphs] when show grades toggled, show grades in graph

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4408]
<img width="1209" alt="image" src="https://github.com/UniversityOfHelsinkiCS/oodikone/assets/523235/4d920f72-4bf2-48d2-855d-eeed4994f5f2">

**Comment by rikurauhala** [comment]
898dd25c3ec2c163ad3e2ca6ec762787490e6b41
