### ISSUE TITLE
Modify workflow so that tests can be run in other branches and PR

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4431]
The tests currently build and push images to registry, we don't want this if we run them in non-master branches or pull requests, and then probably use them in the tests - this is probably not good because the PR / non-master workflows can push images that are then pulled by master which has different code.

Make a new workflow only for testing in non-master branches, or possibly rework the testworkflow in a larger way

**Comment by valtterikantanen** [comment]
Tests and linting are now run for PRs to `master`, I think this is enough for now
