### ISSUE TITLE
custom population broken?

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/oodikone#4436]
After inserting desired student numbers and clicking "search population", oodikone goes back to "custom population main page":

Custom population

Here you can create custom population using a list of studentnumbers. Clicking the blue custom population button will open a modal where you can enter a list of studentnumbers. You can also save a custom population by giving it a name and clicking the save button in the modal. It will then appear in the saved populations list. These populations are personal meaning that they will only show to you. You can only search studentnumbers you have access rights to i.e. you have rights to the programme they are in.

**Comment by ShootingStar91** [comment]
There should be a notification that lists the students that could not be shown and explains the reason (no rights / not correct studentnumbers). In this case user had no right. The notification was broken, but a fix is now pushed to code and will be released soon.
