### ISSUE TITLE
[Course statistics] Provider organization toggle bug

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4438]
Look at course MAT12001 with combine substitutions enabled.

For years 2022 -> there will be no passes of the course. The difference from that year is that the AY-code is not used anymore, and the stats seem to look for that code:
![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/46905824/f59acd05-342e-4736-b2ea-da6c5f8f1a95)

Look at the codes for the last two years (yearcode 73 and 74) which are 2022-2023 and 2023-2024. Those are MAT12001 instead of AYMAT12001, and those have 0 passes (even though there actually are passes for that code and years).

The backend code, probably in src/services/courses/index.js is probably faulty. The provider organization should be looked correctly, instead of trying to use AY-code which is not used after 2022.

**Comment by valtterikantanen** [comment]
Apparently this has been fixed in some point because currently the stats are displayed for all the years and also course population for each year works.
