### ISSUE TITLE
when viewing "all classes" population & general student information columns: start of studyright / started in programme breaks

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/oodikone#4450]
https://oodikone.helsinki.fi/populations?months=80&semesters=FALL&semesters=SPRING&studyRights=%7B%22programme%22%3A%22KH70_004%22%7D&year=All&years=2017&years=2018&years=2019&years=2020&years=2021&years=2022&years=2023

TARKENNE: 
- toimii chromella mutta ei firefoxilla eikä safarilla

![2024-03-20_class_of_all_broken](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/43775188/0285434b-0a0e-4bdb-bd0e-c2f9d4a25fc2)

**Comment by rikurauhala** [comment]
f81cbe1d4f1cf38ba007592a5d7e477dda115e4c
