### ISSUE TITLE
[studyright element] starting date

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4454]
see eg studyright `otm-3f05b783-6a29-4fb4-a7e3-d55b5b4832dc-1`

<img width="1069" alt="image" src="https://github.com/UniversityOfHelsinkiCS/oodikone/assets/523235/6695b393-dbad-42ff-92e6-e82926bb88dc">

is the sre starting date used anywhere? if not, should we start using same in sr and sre 🤔

**Comment by valtterikantanen** [comment]
Studyright element start date is used for example in student page so we need both. The studyright start date and studyright element start date are different if a student changes their degree programme within the same studyright (for example from MAT to TKT).

However, if the studyright element start date is earlier then studyright start date, then studyright start date will be used (that is the case in the picture).
