### ISSUE TITLE
Population view: add gender and (possible) study track to the Student table

### ISSUE THREAD

**Issue by tttriple** [UniversityOfHelsinkiCS/oodikone#4472]
![2024-04-05_student_add_ons](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/43775188/e38799de-acd8-44c2-af57-876712e1c12f)

- [x] Gender
- [x] Study track

**Comment by rikurauhala** [comment]
The study track column was not visible at all. This has now been fixed. 21fb3041667f990cadd69fad1688fedde58ef4fd
