### ISSUE TITLE
[Class statistics] Add a toggle so that the user can choose if they want to include substitutions in the courses list or not

### ISSUE THREAD

**Issue by valtterikantanen** [UniversityOfHelsinkiCS/oodikone#4531]
- [x] Add a toggle so that the user can choose whether substitutions are displayed or not
- [x] Add a symbol for enrollments (these are already 0's in the Excel file). Use the same icons as in *Completed courses of students*
- [x] Hover texts
   - Grade if there is a grade
   - Enrollment date if there is an active enrollment but no grade yet
   - Otherwise no hover text
- [x] Exported Excel file should reflect these changes
- [x] Update the info box to reflect changes
- [x] Consider the Total column when using the toggle
- [x] Also: why do student number filter on the page and on the SortableTable produce different results? If I use the student number filter, substituted courses are not included, while with filter on the SortableTable they are

**Comment by rikurauhala** [comment]
5f332344d63a15564a4536b3c4634f55b5be56f3
