### ISSUE TITLE
Bug in credits produced, numbers change randomly

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4568]
In credits produced, of SOSK
`/study-programme/KH70_003?p_tab=0
`
We noticed that when we press Update basic info from the update tab, then after it is done, go back to basic tab, refresh page, the numbers sometimes differ from what was shown before without any code changes made in between.

**Comment by valtterikantanen** [comment]
This seems similar to #4156, big refactor might fix this

**Comment by valtterikantanen** [comment]
After the big refactor the calculation seems to be more deterministic. At least after refreshing the credit stats few times for a couple of different study programmes the numbers didn't change at all.
