### ISSUE TITLE
Sosial hög skolan programmes tab showing empty tables

### ISSUE THREAD

**Issue by ShootingStar91** [UniversityOfHelsinkiCS/oodikone#4569]
https://oodikone.helsinki.fi/faculties/H74?p_tab=1

![image](https://github.com/UniversityOfHelsinkiCS/oodikone/assets/46905824/b0671256-cbb2-4f20-8e2a-6b9f77e82a94)

If the faculty only has one bsc programme, we shouldnt show these other empty stats probably?

**Comment by rikurauhala** [comment]
42edf79a39bbffe58a7a5ef620b3926c07c31ac7
