### ISSUE TITLE
[Study programme overview] Make graduation times graphs clearer

### ISSUE THREAD

**Issue by valtterikantanen** [UniversityOfHelsinkiCS/oodikone#4580]
Average graduation times are sometimes a bit unclear. Currently the _Bachelor + master studyright_ graph's start year is student's start year in the bachelor's programme (this is stated in the infobox).

![image](https://github.com/user-attachments/assets/84206c6b-26dd-49f9-b595-eca8d363399b)

Breakdown doesn't have any problems, but if we switch to median times view, things are not so clear anymore:

![image](https://github.com/user-attachments/assets/256d2c07-9b72-4cc1-858b-1065f20692d9)

1. The number of people in a certain year class in the _Bachelor + master studyright_ graph should be rethought. Currently it uses the number of students who started in the master's programme on that particular year but this obviously leads to problems. If we want to keep this information, I think the only reasonable number would be the students who have started in any bachelor's programme on a particular year and then later transferred to this specific master's programme. But even this approach has it's own problems as we can only count students who have already graduated from a bachelor's programme. Those who haven't finished their bachelor's degree cannot be counted because we don't even know which master's programme they are going to choose (most bachelor's programmes have multiple options).
2. Also the percentages on the _Master studyright_ graph are not very good. If there's a percentage, it should probably be calculated with the number of students who only had the master's study right. If we don't do this, the percentage can never be 100% even if everybody with just the master's study right had graduated (unless it's a master's programme to which everyone needs to apply separately).

One possible solution would be to always use the start year in the master's programme as a start year in both graphs. Of course in the _Bachelor + master studyright_ graph we would still use the start date in bachelor's programme to calculate how long it took for the student to graduate.

**Comment by rikurauhala** [comment]
Commit f911ae9d1ced5eed6b29df88c5466ad6bce05327
Release [`3.1.16`](https://github.com/UniversityOfHelsinkiCS/oodikone/releases/tag/3.1.16)
