### ISSUE TITLE
[study programme] average graduation times

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4609]
Add the description to header

![Image](https://github.com/user-attachments/assets/70d6a034-0900-4322-bf31-589ce212ff80)

![Image](https://github.com/user-attachments/assets/3e0d2e1e-0c7c-4021-92b1-c2253eb9fe43)

**Comment by rikurauhala** [comment]
b49b1feff44dab1ea40955279c163e9bd8709170
