### ISSUE TITLE
[courses] numbers fakd

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4611]
the below problem is there also if semesters are not separated

see eg 

https://oodikone.helsinki.fi/coursepopulation?coursecodes=%5B%22TKT10005%22%2C%22TKT20004%22%2C%22TKT200041%22%2C%22TKT200042%22%2C%22TKT100052%22%2C%22TKT100051%22%2C%22TKT10006%22%2C%22BSCS1006%22%5D&from=148&separate=true&to=148&unifyCourses=unifyStats&years=Kev%C3%A4t%202024

https://oodikone.helsinki.fi/coursestatistics?combineSubstitutions=true&courseCodes=%5B%22TKT10006%22%5D&cs_tab=0&separate=true

![Image](https://github.com/user-attachments/assets/cfd087d8-6251-4e24-a6fe-ef7cc13a2705)

see also https://github.com/UniversityOfHelsinkiCS/oodikone/issues/4292

Planned fixes:

**Students**

- [x] **PRIORITY**: numbers must match
- [x] Remove *Eventually* and *On first attempt*

**Attempts**

- [x] Total enrollments should be counted in Total attempts
- [x] Calculate pass rate the same way as in Students tab
- [x] Remove columns *Total enrollments*, *Rejected*, and *Aborted* and only include enrollments with confirmed/enrolled state in *Enrolled* column (should be this way already)

**Comment by rikurauhala** [comment]
Related/duplicate issue #4339

**Comment by rikurauhala** [comment]
Planned fixes:

**Students**

- **PRIORITY**: numbers must match
- Remove *Eventually*
- Replace *On first attempt* with *First attempt %*
- Create a new toggle for number of students
  - Default: one student per row
  - Option: each student is only counted once

**Attempts**

- Total enrollments should be counted in Total attempts

**Comment by rikurauhala** [comment]
No new toggles planned, at least for now. Numbers fixed in release [3.1.2](https://github.com/UniversityOfHelsinkiCS/oodikone/releases/tag/3.1.2)
