### ISSUE TITLE
[course stats] filter noncourses

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#4612]
proper fix for this needed:

![Image](https://github.com/user-attachments/assets/82647eb4-ae05-42a2-a8c5-0ff108b2ae14)

should be counted as the course, now is not :(

**Comment by valtterikantanen** [comment]
Fix was added to updater, it will take a while for all attainments to be updated. Also, the current (wrong) attainments will be removed in a purge in a couple of weeks.
