### ISSUE TITLE
[Population] Remove redundant columns

### ISSUE THREAD

**Issue by rikurauhala** [UniversityOfHelsinkiCS/oodikone#4652]
Remove "Passed after retry" and "Failed multiple times"

**Comment by valtterikantanen** [comment]
Also remove *Students* tab from *Courses of class*. *Courses* tab on *Students* section shows the same data but in a better way

![Image](https://github.com/user-attachments/assets/badf38da-fe42-4b37-8a7a-6f2b58bdf888)

**Comment by rikurauhala** [comment]
Commit 2e760c7473f1f1d93cb186d762c5417bd1255142
Release [3.1.7](https://github.com/UniversityOfHelsinkiCS/oodikone/releases/tag/3.1.7)
