### ISSUE TITLE
[Study programme] Page crashes when excluding graduated

### ISSUE THREAD

**Issue by rikurauhala** [UniversityOfHelsinkiCS/oodikone#4663]
In the `Study tracks and class statistics` tab, the page crashes when the "Graduated excluded" toggle is turned on. This happens for programmes with study tracks.

**Comment by valtterikantanen** [comment]
This also happens for bachelor's programmes with study tracks

**Comment by rikurauhala** [comment]
Commit c9592ba954daa59d13eabbf847ea9972f0d266e7
Release [`3.1.12`](https://github.com/UniversityOfHelsinkiCS/oodikone/releases/tag/3.1.12)
