### ISSUE TITLE
Fix eslint config to work with monorepo

### ISSUE THREAD

**Issue by ikuisma** [UniversityOfHelsinkiCS/oodikone#866]
The VS code ESlint plugin does not work out of the box currently. Some ideas for fixing it:
- ESlint as dependency to root
- Shared workspace config file for VScode
- Change location of lint config files

**Comment by Rochet2** [comment]
node_modules is empty for me at least for all of the services.
I think this breaks autocomplete and eslint. eslint should be enough to be in the node_modules in general if you open vscode to the service folder (for example `/services/oodikone2-frontend`)

**Comment by ikuisma** [comment]
@Rochet2 fixed this with changes to CDE
