### ISSUE TITLE
some students do not get right study track

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#868]
MH70_008 Sosiaalitieteiden maisteriohjelma
->ohjelman suunta "SH70_069 sosiaalityö" ei näy Oodikoneessa?
Opiskelija jolla Oodissa MH70_008 ja SH70_069: 0*******7 (suunta kirjattu 1.8.2017)

->ohjelman suunta "SH70_070 sosiologia" ei näy Oodikoneessa?
Opiskelija jolla Oodissa MH70_008 ja SH70_070: 0*******3 (suunta kirjattu 13.5.2018)

MH70_008 Sosiaalitieteiden maisteriohjelmassa 2017-2018 on 60 opiskelijaa ja Oodikoneen mukaan 30:llä ei ole suuntaa. Kuitenkin kun tein satunnaistarkastelua näiden 30 osalta, heillä oli Oodiin kirjattu jompi kumpi yllämainituista suunnista

**Comment by tttriple** [comment]
ongelma korjatunut
