### ISSUE TITLE
bug/fundamental issue: Graduated in time doesnt make any sense right now

### ISSUE THREAD

**Issue by sasumaki** [UniversityOfHelsinkiCS/oodikone#953]
Should it be 5, 3 or 2 years and how do we know?

**Comment by tttriple** [comment]
This is done in Rapo (raportit toiminnasta ja taloudesta):
Tämä analyysi on toteutettu laskemalla tutkintoon käytetyt läsnäololukukaudet ja vertaamalla niitä ylemmän korkeakoulututkinnon tavoiteaikaan, joka on pääsääntöisesti neljä lukukautta, tai alemman ja ylemmän korkeakoulututkinnon yhteiseen tavoiteaikaan, joka on pääsääntöisesti kymmenen lukukautta.
Poikkeuksena tähän ovat psykologian maisterin (5 lukukautta tai 11 lukukautta), eläinlääketieteen lisensiaatin (12 lukukautta), lääketieteen lisensiaatin (12 lukukautta) ja hammaslääketieteen lisensiaatin (10 lukukautta) tutkinnot (tavoiteaika suluissa). Laskennassa ei ole huomioitu niitä poissaololukukausia, jotka kuluttavat tavoiteaikaa.
