### ISSUE TITLE
uh raports: number of students who can not graduate since they have given up studyright

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#961]
number of students 
- transferred to other study programme
- how have stopped studies (study right ended) and not graduated

how to treat those who have studyright cancelled (= eivät ole ilmoittautuneet ajoissa)?
-> do not count to this number, perhaps a separate column?

**Comment by tttriple** [comment]
@mluukkai @sasumaki 

Taulussa opinoik on kenttä opinoikasem, jolla voi olla seuraavia arvoja:

arvo, kieli, alkpvm paatpvm, selite
1    1    01.01.1900    21.12.2112    Ensisijainen
2    1    01.01.1900    21.12.2112    Toissijainen
3    1    01.01.1900    21.12.2112    Ei käytössä
4    1    01.01.1900    21.12.2112    Siirretty toiseen koulutusohjelmaan
5    1    01.01.1900    21.12.2112    Luopunut
6    1    01.01.1900    21.12.2112    Optio
30    1    01.01.1900    21.12.2112    Suorittanut tutkinnon

Näistä 5, eli luopunut on sellaiset, jotka eivät enää "pääse takaisin".
