### ISSUE TITLE
UH raports: median time also for populations

### ISSUE THREAD

**Issue by mluukkai** [UniversityOfHelsinkiCS/oodikone#972]
how to caclulate for studets who have transferred?

![image](https://user-images.githubusercontent.com/523235/58866538-77e7c980-86c1-11e9-8a3c-7c0512dc6f4f.png)

**Comment by sasumaki** [comment]
Median or mean time? Do we really want *also* for popualtion or just instead of productivity?

**Comment by mluukkai** [comment]
*median*
